services:
  playzone_web:
    container_name: playzone_web
    build:
      context: ./docker
    restart: unless-stopped
    env_file:
      - ./.env
      - ./.env.db
    ports:
      - "5678:5678"
      - "8000:8000"
    volumes:
      - ./playzone:/home/app/web

  playzone_db:
    container_name: playzone_db
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ./.env.db
    volumes:
      - playzone_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  playzone_data:
