services:
  db:
    image: postgres:16
    container_name: playzone_db
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: playzone_web
    restart: unless-stopped
    env_file:
      - .env
      - .env.db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
