# Generated by Django 5.2.8 on 2026-01-12 15:23

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Desporto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("preco_hora", models.DecimalField(decimal_places=2, max_digits=6)),
                ("estado", models.CharField(max_length=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("desportos", models.ManyToManyField(to="campos.desporto")),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("duracao_horas", models.PositiveSmallIntegerField(default=1)),
                ("estado", models.CharField(max_length=20)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campos.campo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]