# Generated by Django 5.2.10 on 2026-01-13 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={'verbose_name': 'Campo', 'verbose_name_plural': 'Campos'},
        ),
        migrations.AlterModelOptions(
            name='desporto',
            options={'verbose_name': 'Desporto', 'verbose_name_plural': 'Desportos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data', '-hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='campo',
            name='desportos',
            field=models.ManyToManyField(related_name='campos', to='campos.desporto'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='estado',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='campo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='desporto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='campos.campo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('RESERVADA', 'Reservada'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída')], default='RESERVADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
    ]
