# Generated by ChatGPT on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campos", "0002_alter_campo_options_alter_desporto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campo",
            name="foto",
            field=models.CharField(
                blank=True,
                default="images/campos/desportivo-de-futebol.avif",
                max_length=255,
            ),
        ),
    ]
